- docs/conf.py
> docs: fix "fork me on GitHub" ribbon

- Dockerfile
- reana_job_controller/app.py
- reana_job_controller/k8s.py
- reana_job_controller/volume_templates.py
> docs: more copyright header messages

- reana_job_controller/app.py
- reana_job_controller/k8s.py
- reana_job_controller/volume_templates.py
- run-tests.sh
* Adds API documentation. (closes #6)
* Adds docstrings and plugs pydocstyle. (closes #10)
> docs: improve documentation

- CONTRIBUTING.rst
- README.rst
- docs/conf.py
- docs/contributing.rst
- docs/gettingstarted.rst
- docs/index.rst
- docs/introduction.rst
- docs/restapi.rst
- docs/usage.rst
- reana_job_controller/app.py
- setup.py
- b31c9d811bc9d532571c7d131ed9ed02d02196ad docs: addition of Travis/Coveralls/RFTD/Waffle/Travis/License badges
- f901df93d1254dfbb1bf806b4468c6b4b0f2bd73 docs: more structured chapters
- 870668f2def8c574b7d7a5d294d09b58a921969e docs: addition of REST API documentation
> docs: addition of REST API documentation

- reana_job_controller/k8s.py
- reana_job_controller/volume_templates.py
* Detects which storage backend should be configured using the
`STORAGE_BACKEND` env variable instead of hardwiring CEPHFS.
(closes #37)
> storage: set backend depending on env var

- setup.py
> docs: pin sphinx to avoid build failure

- CHANGES.rst
- reana_job_controller/version.py
> release: v0.1.0

- reana_job_controller/version.py
> version: post-release bump

- AUTHORS.rst
- CHANGES.rst
- docs/openapi.json
- reana_job_controller/version.py
> release: v0.2.0

- AUTHORS.rst
- reana_job_controller/version.py
> docs: author ORCID links

- docs/openapi.json
- reana_job_controller/app.py
- reana_job_controller/k8s.py
- reana_job_controller/schemas.py
* Adds operation ids to get_jobs() and
get_logs() methods.
Co-authored-by: Diego Rodriguez <diego.rodriguez@cern.ch>
> rest: addition of operation_ids

- docs/openapi.json
- reana_job_controller/app.py
- reana_job_controller/schemas.py
> openapi: remove workflow_uuid

- reana_job_controller/k8s.py
> k8s: store finished job logs in DB

- Dockerfile
- docs/openapi.json
- reana_job_controller/app.py
- reana_job_controller/schemas.py
depends on https://github.com/reanahub/reana-commons/pull/22, https://github.com/reanahub/reana-cluster/pull/93, https://github.com/reanahub/reana-commons/pull/29
addresses #76
> global: job caching

- reana_job_controller/app.py
- reana_job_controller/k8s.py
- reana_job_controller/volume_templates.py
Connect https://github.com/reanahub/reana-workflow-controller/issues/108.
> templates: remove experiment/org specific dir

- docs/openapi.json
- reana_job_controller/app.py
- reana_job_controller/schemas.py
Connect reanahub/reana-client#126.
> api: add job_name and prettified_cmd to create_job

- .travis.yml
- Dockerfile
- docs/requirements.txt
- reana_job_controller/app.py
- reana_job_controller/k8s.py
- requirements-dev.txt
- setup.py
> installation: REANA-DB and REANA-Commons splitted

- reana_job_controller/k8s.py
> docs: remove reference to unused pykube

- CHANGES.rst
- Dockerfile
- docs/requirements.txt
- reana_job_controller/app.py
- reana_job_controller/spec.py
- reana_job_controller/version.py
- requirements-dev.txt
- setup.py
> release: v0.3.0

- setup.py
* Introduces upper boundaries for REANA-Commons and REANA-DB dependency
versions. (addresses reanahub/reana#80)
> installation: setup.py for REANA-Commons and REANA-DB

- CHANGES.rst
- README.rst
- reana_job_controller/version.py
> release: v0.3.1

- Dockerfile
- reana_job_controller/volume_templates.py
> volume_templates: cephfs template pvc

- docs/conf.py
- docs/restapi.rst
- run-tests.sh
- setup.py
* Improves REST API docs rendering. Closes reanahub/reana#25
> docs: improve sphinxcontrib-openapi rendering

- docs/conf.py
- docs/openapi.json
- docs/restapi.rst
- reana_job_controller/app.py
* Fix navigation. Harmonise title/description text in Python docstring
and OpenAPI. Closes #95
> docs: better navigation and synced descriptions

- AUTHORS.rst
- CHANGES.rst
- reana_job_controller/version.py
- setup.py
> release: v0.4.0

- reana_job_controller/config.py
- reana_job_controller/k8s.py
- reana_job_controller/volume_templates.py
Connects https://github.com/reanahub/reana-cluster/issues/131
> volume_templates: cvmfs

- Dockerfile
* Fix from https://github.com/reanahub/reana-workflow-controller/issues/173.
> docker: remove no cache dir flag

- setup.py
> installation: bump db and commons

- docs/openapi.json
- reana_job_controller/job_db.py
- reana_job_controller/k8s.py
- reana_job_controller/rest.py
- reana_job_controller/schemas.py
- reana_job_controller/volume_templates.py
- setup.py
* Modifies cvmfs_mounts field in Job and JobRequest schemas from
array to boolean.
Connect https://github.com/reanahub/reana-cluster/issues/154
> global: cvmfs_mounts to boolean

- Dockerfile
- reana_job_controller/k8s.py
- setup.py
> docker: slimmer image

- reana_job_controller/factory.py
> logging: logging format from R-Commons

- reana_job_controller/factory.py
- setup.py
- tests/conftest.py
* Adding pytest-reana support. Closes #120
Signed-off-by: roma0851 <rokas.maciulaitis@cern.ch>
> tests: use of pytest-reana

- reana_job_controller/job_manager.py
- setup.py
- tests/test_job_manager.py
* Test for kubernetes job stop & fixes for kubernetes
job execution test. Closes #122
> test: adding stop k8s job test

- .travis.yml
- AUTHORS.rst
- CHANGES.rst
- docs/conf.py
- docs/developerguide.rst
- docs/openapi.json
- reana_job_controller/spec.py
- reana_job_controller/version.py
- setup.py
> release: v0.5.0

- docs/openapi.json
- reana_job_controller/config.py
- reana_job_controller/factory.py
- reana_job_controller/job_manager.py
- reana_job_controller/kubernetes_job_manager.py
- reana_job_controller/rest.py
- tests/test_views.py
> config: setting default job backend

- setup.py
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>
> cluster: bump reana-commons version

- reana_job_controller/config.py
- reana_job_controller/htcondorcern_job_manager.py
- reana_job_controller/kubernetes_job_manager.py
- setup.py
> global: adds 1st prototype for condor job submission

- reana_job_controller/kubernetes_job_manager.py
- setup.py
- tests/test_job_manager.py
* Adresses reanahub/reana-job-controller#147
> secrets: mount secrets in jobs

- reana_job_controller/rest.py
- reana_job_controller/utils.py
- tests/conftest.py
- tests/test_views.py
> rest: adds log message in case not supported backend

- docs/developerguide.rst
* Closes reanahub/reana-client#306
> docs: change docs to comply with the new secrets cli format

- reana_job_controller/config.py
- reana_job_controller/factory.py
- reana_job_controller/htcondorcern_job_manager.py
- reana_job_controller/job_monitor.py
- reana_job_controller/rest.py
- tests/conftest.py
- tests/test_job_monitor.py
* job monitor threads are initialized through singelton classes
> job_monitor: refactoring job monitors

- MANIFEST.in
- docs/openapi.json
- krb5/Dockerfile
- reana_job_controller/config.py
- reana_job_controller/kubernetes_job_manager.py
- reana_job_controller/rest.py
- reana_job_controller/schemas.py
> kubernetes: add sidecar container for managing krb5

- docs/developerguide.rst
- reana_job_controller/htcondorcern_job_manager.py
- reana_job_controller/job_monitor.py
- setup.py
> htcondor: job monitoring & docs fix

- reana_job_controller/kubernetes_job_manager.py
> kubenetes_job_manager: renames job container

- reana_job_controller/job_monitor.py
- reana_job_controller/utils.py
- setup.py
> utils: adds ssh client prototype

- reana_job_controller/factory.py
- reana_job_controller/htcondorcern_job_manager.py
- reana_job_controller/job_monitor.py
- reana_job_controller/rest.py
- reana_job_controller/utils.py
- tests/test_job_monitor.py
> htcondor: testing singlethreaded htcondor operations

- reana_job_controller/htcondorcern_job_manager.py
> htcondor: adds user logs in case of authentication failures

- reana_job_controller/job_monitor.py
> job_monitor: saves krb5 container logs to user logs

- Dockerfile
- reana_job_controller/kubernetes_job_manager.py
- setup.py
* Addresses reanahub/reana-workflow-controller/issues/231
> k8s: refactors volume mounts

- Dockerfile
- docs/developerguide.rst
- reana_job_controller/config.py
- reana_job_controller/htcondorcern_job_manager.py
- reana_job_controller/job_monitor.py
- reana_job_controller/kubernetes_job_manager.py
- reana_job_controller/rest.py
- reana_job_controller/slurmcern_job_manager.py
- reana_job_controller/utils.py
- setup.py
- tests/test_job_monitor.py
> slurm: 1st prototype

- reana_job_controller/config.py
- reana_job_controller/job_monitor.py
- reana_job_controller/kubernetes_job_manager.py
- setup.py
> k8s: add EOS volume to jobs if available

- docs/openapi.json
- reana_job_controller/htcondorcern_job_manager.py
- reana_job_controller/job_db.py
- reana_job_controller/job_manager.py
- reana_job_controller/job_monitor.py
- reana_job_controller/kubernetes_job_manager.py
- reana_job_controller/rest.py
- reana_job_controller/schemas.py
- reana_job_controller/slurmcern_job_manager.py
* Addresses reanahub/reana-workflow-controller/issues/269
> rest: cleans job request & allows overwriting uid

- etc/job_wrapper.sh
- reana_job_controller/htcondorcern_job_manager.py
- reana_job_controller/job_monitor.py
* Closes https://github.com/reanahub/reana-demo-root6-roofit/issues/36
& https://github.com/reanahub/reana-client/issues/343
> htcondor: fixes bash characters escaping & not found job log files

- reana_job_controller/kubernetes_job_manager.py
> volumes: CVMFS readOnly to true on job pod spec

- setup.py
* Addresses reanahub/reana-workflow-controller/issues/289
> installation: shared packages version bump

- reana_job_controller/job_manager.py
- setup.py
* Addresses reanahub/reana-workflow-controller/issues/289
> job_manager: changes get_workspace method with worksapce_path field

- setup.py
* New version 1.0 of Werkzeug released.
> installation: pin werkzeug

- reana_job_controller/job_monitor.py
* In case user provides the image name with a typo workflow fails
and saves the proper msg in the logs.
Closes #3
> job_monitor: fix for not valid image name

- reana_job_controller/job_monitor.py
> job_monitor: catch wrong image tag failures

- docs/openapi.json
- reana_job_controller/htcondorcern_job_manager.py
- reana_job_controller/kubernetes_job_manager.py
- reana_job_controller/schemas.py
- reana_job_controller/slurmcern_job_manager.py
> htcondor: allows to run jobs with unpacked imgages from cvmfs

- reana_job_controller/config.py
- reana_job_controller/kubernetes_job_manager.py
Closes reanahub/docs.reana.io#18.
> config: get krb5 configmap name from env

- reana_job_controller/config.py
- reana_job_controller/factory.py
- reana_job_controller/job_monitor.py
- run-tests.sh
- tests/conftest.py
- tests/test_job_monitor.py
- Closes #250
- Addresses #249
> job_monitor: fix monitor initialisation

- CHANGES.rst
- README.rst
- docs/conf.py
- pytest.ini
- reana_job_controller/__init__.py
- reana_job_controller/app.py
- reana_job_controller/cli.py
- reana_job_controller/config.py
- reana_job_controller/factory.py
- reana_job_controller/htcondorcern_job_manager.py
- reana_job_controller/job_db.py
- reana_job_controller/job_manager.py
- reana_job_controller/job_monitor.py
- reana_job_controller/kubernetes_job_manager.py
- reana_job_controller/rest.py
- reana_job_controller/schemas.py
- reana_job_controller/slurmcern_job_manager.py
- reana_job_controller/spec.py
- reana_job_controller/utils.py
- run-tests.sh
- setup.py
- tests/conftest.py
- tests/test_job_manager.py
- tests/test_job_monitor.py
- tests/test_openapi_spec.py
- tests/test_version.py
- tests/test_views.py
> global: Black support

- reana_job_controller/kubernetes_job_manager.py
Set security context on pod level so that job and init containers have uid self.kubernetes_uid and gid `WORKFLOW_RUNTIME_USER_GID` (currently set to 0 in `reana_commons/config.py`).
Since secrets by default has permissions `0644` (drw-r--r--  root root), the voms proxy init container can read from secrets (needs to copy a file from secrets to /tmp) having uid != 0 but gid = 0.
This then also fixes the issue for the kr5b init container that needs uid self.kubernetes_uid to create the ticket in the correct location.
closes reanahub/reana#313
> krb5: set security context on pod level

- reana_job_controller/config.py
- run-tests.sh
- setup.py
- tests/conftest.py
partially addresses reanahub/reana#348
> tests: move to containerised postgres DB

- .travis.yml
- CHANGES.rst
- Dockerfile
- requirements.txt
- setup.py
> migrate to python 3.8

- krb5/Dockerfile
- reana_job_controller/config.py
* Addresses reanahub/reana-auth-krb5#1.
> docker: move kerberos5 image to different repo

- reana_job_controller/config.py
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>
> auth: use new reana-auth-krb5 1.0.1 image

- reana_job_controller/job_monitor.py
* Cause of the error, race condition in Slurm DB. Job IDs are reused,
and because we query very fast, we query an old completed job. However
the real job submited by us is not even started. Technically speaking
sacct queries `slurmdbd` but the job we submitted is still only in
memmory, `slurmctld`, not yet committed to DB, where the old ID lays.
Options:
- Tried in this commit: specifying a date to sacct so no old jobs
are retrieved. This is not very stable, because how long in the
past should we look? maybe the pod dies and has to check for old
jobs...
- Use `scontrol show job` because it uses slurmctld directly and
has the latest and greatest data.
Closes #272.
> slurm: protect against race condition in Slurm

- reana_job_controller/job_monitor.py
> job_monitor: expect potential empty statuses

- .flake8
- .github/workflows/ci.yml
- Dockerfile
- MANIFEST.in
- README.rst
- reana_job_controller/htcondorcern_job_manager.py
- reana_job_controller/kubernetes_job_manager.py
- run-tests.sh
- setup.py
- tests/test_job_monitor.py
addresses https://github.com/reanahub/reana/issues/450
> ci: add hadolint and flake8 linters

- CHANGES.rst
- docs/openapi.json
- reana_job_controller/job_monitor.py
- reana_job_controller/rest.py
- requirements.txt
- setup.py
- tests/test_job_monitor.py
* Addresses reanahub/reana#461.
> kubernetes: configurable job cleanup 

- CHANGES.rst
- Dockerfile
- etc/myschedd.yaml
- reana_job_controller/htcondorcern_job_manager.py
Upgrades myschedd package and configuration, following CERN LXPLUS
setup.
> htcondorcern: myschedd upgrade

- CHANGES.rst
- reana_job_controller/htcondorcern_job_manager.py
- reana_job_controller/job_manager.py
- reana_job_controller/kubernetes_job_manager.py
- reana_job_controller/schemas.py
- reana_job_controller/slurmcern_job_manager.py
- requirements.txt
- setup.py
- tests/test_job_manager.py
- tests/test_views.py
> global: harmonise job command treatment

- CHANGES.rst
- Dockerfile
- docs/openapi.json
- etc/myschedd.yaml
- reana_job_controller/htcondorcern_job_manager.py
- reana_job_controller/version.py
- requirements.txt
- setup.py
Closes https://github.com/reanahub/reana/issues/512
> release: 0.8.0a3

- docs/openapi.json
- reana_job_controller/version.py
- requirements.txt
- setup.py
- installation: bump shared modules
- release: 0.8.0a4
> release 0.8.0a4

- CHANGES.rst
- docs/openapi.json
- reana_job_controller/config.py
- reana_job_controller/htcondorcern_job_manager.py
- reana_job_controller/job_monitor.py
- reana_job_controller/kubernetes_job_manager.py
- reana_job_controller/rest.py
- reana_job_controller/schemas.py
- reana_job_controller/slurmcern_job_manager.py
- tests/test_job_monitor.py
- tests/test_views.py
closes #343 
closes #351
How to test:
This PR is part of a bigger group of PRs. Please refer to the addressed issue to see all of them.
Detailed instructions are presented in Yadage, CWL, Serial, and Snakemake PRs.
> add kubernetes_job_timeout

- reana_job_controller/cli.py
- requirements.txt
- setup.py
closes https://github.com/reanahub/reana-job-controller/issues/360
> setup: upgrade to Flask v2

- AUTHORS.rst
- reana_job_controller/config.py
- reana_job_controller/kubernetes_job_manager.py
- requirements.txt
- setup.py
- tests/test_job_manager.py
Closes reanahub/reana-workflow-engine-snakemake#44
> k8s-job-manager: use `reana-commons` to generate Kerberos configuration

- CHANGES.rst
- Dockerfile
- requirements.txt
- setup.py
> installation: bump htcondor to 9.0.0

- docs/openapi.json
- reana_job_controller/version.py
- requirements.txt
- setup.py
- installation: bump shared modules
- release: 0.9.1a2
> release 0.9.1a2

- CHANGES.rst
- Dockerfile
- requirements.txt
- run-tests.sh
- setup.py
> docker: fix build on arm64 architecture

- CHANGES.rst
- reana_job_controller/job_monitor.py
- reana_job_controller/kubernetes_job_manager.py
- requirements.txt
- setup.py
- k8s: allow automounting of CVMFS repositories
- job-manager: handle pod creation errors
- job-monitor: handle invalid pod configuration
Closes reanahub/reana-commons#423
> k8s: allow automounting of CVMFS repositories

- CHANGES.rst
- Dockerfile
- docs/openapi.json
- reana_job_controller/version.py
- requirements.txt
- setup.py
> release: 0.9.2

- reana_job_controller/config.py
- reana_job_controller/job_manager.py
- tests/test_job_manager.py
> perf(cache): avoid caching jobs when the cache is disabled (#435)

- Dockerfile
- reana_job_controller/config.py
- reana_job_controller/kubernetes_job_manager.py
- reana_job_controller/rest.py
- setup.py
Cache user secrets to avoid fetching them multiple times when creating
many jobs.
Closes reanahub/reana-commons#455
> perf(secrets): avoid fetching k8s secrets multiple times (#451)

- reana_job_controller/config.py
- reana_job_controller/factory.py
> perf(config): make closing of database connections optional (#463)

- reana_job_controller/config.py
Depends on: 
- #465
- https://github.com/reanahub/reana-auth-vomsproxy/pull/33
> build(deps): update reana-auth-vomsproxy to 1.3.0 

- .github/workflows/ci.yml
- .yamllint.yaml
- AUTHORS.md
- run-tests.sh
> ci(yamllint): add YAML linting
