reanahub/reana-job-controller

docs/requirements.txt
* Adds `docs/requirements.txt` so that ReadTheDocs can install all the
prerequisites for building the autodoc parts of the documentation.
=> docs: ReadTheDocs configuration

config.py, docs/conf.py, reana_job_controller/app.py, reana_job_controller/k8s.py
* Adds `config.py` so that pykube configuration is loaded only at
run time. (closes #18)
* Renames `create_job` on `k8s.py` to avoid name clashing inside
`app.py`.
=> docs: fix ReadTheDocs build

docs/conf.py, docs/gettingstarted.rst, docs/openapi.json, docs/restapi.rst, reana_job_controller/app.py, reana_job_controller/cli.py, reana_job_controller/schemas.py, reana_job_controller/spec.py, run-tests.sh, setup.py, tests/test_openapi_spec.py
* Adds CLI to generate OpenAPI spec out of docstrings.
* Adds initial test to validate spec.
=> api: openapi specification generation

docs/openapi.json, reana_job_controller/app.py, reana_job_controller/k8s.py
=> api: add logging

reana_job_controller/k8s.py
Failed jobs do not fail inside job-controller if they exit with a code different from 1, this PR fails all jobs with exit code other than 0
(if the commit needs rewording, please suggest a proper leading tag)
=> change job failure condition

Dockerfile, reana_job_controller/app.py, setup.py
* The job-watcher thread stops working when running with uwsgi since
all the requests timeout.
=> dockerfile: revert uwsgi due to request timeouts

reana_job_controller/config.py, reana_job_controller/k8s.py, reana_job_controller/volume_templates.py
* Refactors shared file system related variables to a defined mapping
making a clear difference between source path and destination path.
=> config: add mount dest for shared FS

reana_job_controller/k8s.py
* Reverts change done in d660142af4c4eb60d7615fde62a9284a6c47c495
since it breaks `k8s_delete_job` when called from `watch_jobs`
(Closes #101).
=> k8s: return V1Job when creating job

setup.py
* Fixes `master` branch docker image building troubles by restricting upper
version of apispec dependency.
=> installation: upper pin on apispecs

docs/openapi.json, reana_job_controller/config.py, reana_job_controller/k8s.py, reana_job_controller/rest.py, reana_job_controller/schemas.py, reana_job_controller/volume_templates.py
* Previously jobs were having mounted the whole REANA shared file
system. With this fix jobs will be only able to access paths under
the user/workflow owner directory.
=> volume-templates: user directory as root path for jobs

tests/conftest.py
* watch_jobs thread should not be launched by base_app fixture,
because it cause test failures due missing k8s api mocks.
Closes #125
Co-authored-by: Diego Rodriguez <diego.rodriguez.rodriguez@cern.ch>
=> fixture: base_app not lauching watch_jobs thread

reana_job_controller/kubernetes_job_manager.py
* Jobs were not deleted because of wrong parameters passed to the
function (closes #127).
=> k8s: fix delete call arguments

reana_job_controller/kubernetes_job_manager.py
* Before all the secrets, regardless of their type, were mounted as files
* Closes reanahub/reana-workflow-controller#222
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>
=> secrets: mount only file-type secrets

reana_job_controller/htcondorcern_job_manager.py
* CERN HTCondor cluster nodes were migrated to CentOS7,
OS requirement is not needed anymore.
=> HTCondor: no OS requirement

Dockerfile, reana_job_controller/config.py, reana_job_controller/htcondorcern_job_manager.py, reana_job_controller/job_monitor.py, reana_job_controller/rest.py
* Allows user to set compute backend only if multiple compute backend
are set to True. Closes #166
=> rest: Hybrid backend fix

reana_job_controller/config.py, reana_job_controller/kubernetes_job_manager.py
* Administrators may want to mount into the job pods custom paths
which they know are present on every node in the cluster. A good
example good be to make available to all jobs a common volume
such as CVMFS.
=> config: add possibility to mount custom hostPath's

Dockerfile, reana_job_controller/config.py, reana_job_controller/rest.py
global: sets compute backend from docker build arg.
* Closes #170
=> global: sets compute backend from docker build arg.

Dockerfile, reana_job_controller/htcondorcern_job_manager.py, reana_job_controller/job_monitor.py, setup.py
* Only one instance of job monitor was created, but
reinitialization (__init__) was happening multiple times,
which led to multiple job monitor threads.
=> HTCondor: job monitor singleton fix

setup.py
* Unpins urllib3 since it is correctly set as a dependency in the
Python Kubernetes client (addresses reanahub/reana-client#320).
=> installation: unpin urllib3

Dockerfile
* SSH client is needed for  connecting to SLURM submit
node. Connects #71
=> Dockerfile: install ssh client

reana_job_controller/config.py, reana_job_controller/kubernetes_job_manager.py
* Adds the configured image pull secrets to the Kubernetes job
specification, enabling private image usage in REANA (closes #230).
=> kubernetes: pass image pull secrets

docs/openapi.json, reana_job_controller/config.py, reana_job_controller/kubernetes_job_manager.py, reana_job_controller/schemas.py
Sidecar container that creates a proxy certificate when user specifies `proxy: true` in reana.yaml. The pem files needed to create the certificate is added to reana secrets as files, the password is added as an environment variable
reana-client secrets-add --env VOMSPROXY_PASS=<proxy password in base64>\
--file userkey.pem \
--file usercert.pem
The security context was before set on pod level to self.kubernetes_uid (default 1000). To read the pem files inside of reana secrets we need root privileges. Set the security context on container level instead at `reana_job_controller/kubernetes_job_manager.py`. Set the job container to self.kubernetes_uid and leave the sidecar as root.
closes reanahub/reana#256
=> Grid proxy

reana_job_controller/kubernetes_job_manager.py
User might enter their VO in upper case (which is the usual way to write the acronym of the experiments). Add changing environment variable  `VONAME` to lower case every time.
=> voms-proxy: VO always in lower case

.travis.yml, reana_job_controller/job_monitor.py, run-tests.sh, tests/conftest.py, tests/test_job_monitor.py
* On an error scenario inside an init container (usually for
authentication purposes), job pods were in waiting status
(`PodInitializing`) as they were waiting for the init container
to finish, event that would never happen as the init container
fails. This was causing that a call to Kubernetes to retrieve
logs of an uninitialised container was fired, resulting in an
uncatched error and empty logs (close reanahub/reana#284).
=> job-monitor: logs only from terminated containers

reana_job_controller/config.py, reana_job_controller/job_monitor.py, reana_job_controller/rest.py, tests/conftest.py, tests/test_job_monitor.py
* Currently backend specific code was being loaded at import config
time, causing errors when necessary HTCondor was not available
because user workflows were requesting just Kubernetes jobs.
=> config: avoid side-effects when loading config

CHANGES.rst, reana_job_controller/job_monitor.py, reana_job_controller/kubernetes_job_manager.py
* In order to be able to deploy REANA in different Kubernetes
namespaces we use the centrally configured variable from
REANA-Commons which represents it. This configuration happens
at deployment time and can be different than the namespace
in which the REANA infrastructure pods run
(closes reanahub/reana#274, closes reanahub/reana#268).
=> config: use centrally configured k8s namespace

reana_job_controller/config.py, reana_job_controller/kubernetes_job_manager.py
* The format of this configuration gets updated to provide flexibility
regarding where to mount the volumes inside the jobs, with the
`mountPath` field.
=> config: use central optional hostpath mounts

reana_job_controller/kubernetes_job_manager.py, setup.py
* Specifies the configured node selector so the submitted jobs get
scheduled to the correct/configured nodes.
=> kubernetes: use node selectors for jobs

MANIFEST.in, docs/conf.py, reana_job_controller/utils.py, requirements.in, requirements.txt, setup.py
closes #274
Adds mocking of  `gssapi` that cannot be installed on ReadTheDocs
builders.
This fixes the ReadTheDocs building problem.
=> docs: autodoc_mock_imports for gssapi

CHANGES.rst, docs/openapi.json, reana_job_controller/htcondorcern_job_manager.py, reana_job_controller/schemas.py
Add `htcondor_max_runtime` and `htcondor_accounting_group`
Following HTCondor's example max runtime can either be set directly in seconds, or can be assigned a "flavour" which will bucket the job into a max runtime. Job flavours can be found [here](https://batchdocs.web.cern.ch/local/submit.html).
Closes reanahub/reana-job-controller#32
=> Htc resources

Dockerfile
* Avoids installation problems not seen when working inside CERN
network. If your tunneling is turned off, the wget's will fail
with a 403 errors, but the execution won't be stopped, resulting
in an image which won't have the necessary packages to make
HTCondor work at CERN.
=> dockerfile: exit on myschedd installation errors

reana_job_controller/kubernetes_job_manager.py
* Avoids default automounting of Kubernetes API tokens inside
user jobs (more [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server))
as it may represent a security hazard.
=> kubernetes: do not mount K8S API token on jobs

CHANGES.rst, reana_job_controller/job_monitor.py
* The workspace of HTCondor jobs was not retrieved in case of job
failure, causing error "file not found *.err *.out" when trying
to store logs to later display to the user (closes #301).
Closes #301.
=> htcondor: retrieve files always

CHANGES.rst, docs/openapi.json, reana_job_controller/config.py, reana_job_controller/job_monitor.py, reana_job_controller/kubernetes_job_manager.py, reana_job_controller/version.py
* Informs users better about jobs that are terminated by external
reasons (e.g. OOMKilled) (addresses reanahub/reana#490).
=> kubernetes: improve job failed logs

reana_job_controller/kubernetes_job_manager.py, requirements.txt
Closes reanahub/reana#493.
CI blocked by https://github.com/reanahub/reana-commons/pull/257 release.
=> k8s: set specific node label for jobs

CHANGES.rst, docs/openapi.json, reana_job_controller/config.py, reana_job_controller/kubernetes_job_manager.py, reana_job_controller/rest.py, reana_job_controller/schemas.py, requirements.txt, setup.py, tests/test_job_manager.py
closes reanahub/reana-client#496
⚠️ Tests failing due to missing `reana-commons` release.
- Set a cluster-wide memory limit to verify that is override. If you don't have a multinode cluster setup, comment out the check that forces you to have `node_label_runtime` when setting `kubernetes_jobs_memory_limit`:
```diff
diff --git a/helm/reana/templates/reana-workflow-controller.yaml b/helm/reana/templates/reana-workflow-controller.yaml
index c565512..c35b77c 100644
--- a/helm/reana/templates/reana-workflow-controller.yaml
+++ b/helm/reana/templates/reana-workflow-controller.yaml
@@ -80,7 +80,6 @@ spec:
value: {{ .Values.node_label_runtime }}
{{- end }}
{{- if .Values.kubernetes_jobs_memory_limit }}
-          {{- $_ := required "In order to use .Values.kubernetes_jobs_memory_limit safely you …
```
=> k8s: allow customising job memory limit

CHANGES.rst, Dockerfile, etc/myschedd.yaml, reana_job_controller/htcondorcern_job_manager.py, requirements.txt, setup.py
Upgrades HTCondor to 8.9.11, following up the upgrade of CERN HTCondor
cluster.
Removes ClassAd HTCondor version constraint that is no longer necessary.
Updates myschedd package and configuration to latest LXPLUS values.
Updates ngbauth-submit package to latest LXPLUS value.
=> htcondorcern: upgrade to 8.9.11

reana_job_controller/htcondorcern_job_manager.py
closes https://github.com/reanahub/reana-workflow-engine-cwl/issues/186
CWL job commands are [formatted as strings](https://github.com/reanahub/reana-workflow-engine-cwl/blob/master/reana_workflow_engine_cwl/cwl_reana.py#L254) in `reana-workflow-engine-cwl`, but `htcondorcern_job_manager (reana-job-controller)` [expected a list here](https://github.com/reanahub/reana-job-controller/blob/master/reana_job_controller/htcondorcern_job_manager.py#L169). 
That's why the error was `i: command not found`, since the second element of job command string `"/bin/sh...."` is `i`.
With this fix `reana-demo-helloworld/reana-cwl-htcondorcern.yaml` example worked as expected
=> htcondorcern: fixed job command formatting issue for CWL workflows

Dockerfile
`reana-dev docker-build -c r-j-controller -b COMPUTE_BACKENDS=kubernetes,slurmcern,htcondorcern` fails otherwise.
PS. When running the command above, remember to set SSH tunnel.
=> docker: pin base image

reana_job_controller/rest.py
closes https://github.com/reanahub/reana-workflow-controller/issues/408
To test:
- Change [max-connections](https://github.com/reanahub/reana/blob/master/helm/reana/templates/reana-db.yaml#L37) value to 5 and redeploy the cluster
- Run `helloworld` demo and check the logs:
```
reana ❯ rc logs -w workflow.1
==> Workflow engine logs
Workflow exited unexpectedly.
Job submission error: Job submission failed because of DB connection issues.
(psycopg2.OperationalError) FATAL:  sorry, too many clients already
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```
=> rest: catch and expose DB connection troubles

reana_job_controller/job_monitor.py, reana_job_controller/kubernetes_job_manager.py
Context: https://github.com/reanahub/reana-workflow-controller/pull/417#discussion_r742147129
=> job-monitor: rename job pod labels to be in line with run batch labels

reana_job_controller/factory.py, reana_job_controller/job_manager.py
close https://github.com/reanahub/reana-job-controller/issues/325
The problem was that `job-controller` started a new DB session on initial job creation and removed the connection only when the app [was terminated](https://github.com/reanahub/reana-job-controller/blob/master/reana_job_controller/factory.py#L43). This lead to creation of multiple db connections while launching many workflows and it meant that we can only launch as many workflows in parallel as we have [db connections](https://github.com/reanahub/reana/pull/542).
This PR tries to release the DB connection as soon as it is no longer needed: after each request and especially after [job registration in the DB](https://github.com/reanahub/reana-job-controller/blob/master/reana_job_controller/job_manager.py#L65-L66) (main …
=> db: close db connections after each request

reana_job_controller/kubernetes_job_manager.py
How to test:
1. Modify `reana-demo-helloworld`
```diff
--- a/reana.yaml
+++ b/reana.yaml
@@ -14,6 +14,7 @@ workflow:
steps:
- environment: 'python:2.7-slim'
commands:
+          - env
- python "${helloworld}"
--inputfile "${inputfile}"
--outputfile "${outputfile}"
```
2. Execute the modified `reana-demo-helloworld`
3. Check the steps logs
Expected result: k8s environment variables used for service discovery, such as `REANA_SERVER_SERVICE_HOST`, are not present in the environment of the jobs pods
=> k8s-job-manager: disable k8s env variables in job's pod

CHANGES.rst, docs/openapi.json, reana_job_controller/config.py, reana_job_controller/job_monitor.py, reana_job_controller/rest.py, reana_job_controller/schemas.py, reana_job_controller/slurmcern_job_manager.py, reana_job_controller/utils.py
closes https://github.com/reanahub/reana-job-controller/issues/206
closes https://github.com/reanahub/reana-job-controller/issues/345
How to test:
- mock that you have Slurm cluster locally:
- add `slurmcern` [here](https://github.com/reanahub/reana/blob/master/helm/reana/values.yaml#L19) and redeploy the cluster
- modify [this line](https://github.com/reanahub/reana-job-controller/blob/master/reana_job_controller/config.py#L50) to:
```python
SUPPORTED_COMPUTE_BACKENDS = ["kubernetes", "slurmcern"]
```
- place `wdb` breakpoint after setting the new configuration values [here](https://github.com/reanahub/reana-job-controller/pull/366/files#diff-cf7e1e5f5cc1e24ef851d65c6116c60cdfd9402ac75ce619a574f591b1b750f5R95)
- run some examples and set the new configurations as described in the [docs …
=> slurm: expose some of the job configuration to users

CHANGES.rst, reana_job_controller/config.py
Upgrades to the latest reana-env-vomsproxy in order to have proper
ESCAPE VOMS support.
=> config: vomsproxy sidecar upgrade

AUTHORS.rst, CHANGES.rst, docs/openapi.json, reana_job_controller/config.py, reana_job_controller/kubernetes_job_manager.py, reana_job_controller/schemas.py
Closes reanahub/reana-auth-rucio#1
=> rucio: integrate sidecar container

CHANGES.rst, reana_job_controller/config.py, reana_job_controller/kubernetes_job_manager.py
Allows respecting user-generated VOMS proxy file technique:
- If a user generates VOMS proxy file on the client side, and uploads it as a user secret in a file specified by VOMSPROXY_FILE, then this file is reused in the sidecar. This mode is suitable for multi-user REANA deployments where users wouldn't trust to upload their Grid certificate details as Kubernetes secret.
- Otherwise if VOMSPROXY_FILE does not exist, we fall back to generating the VOMS proxy file inside the sidecar, as before. This mode is suitable for single-user REANA deployments where the user doesn't hesitate to upload their Grid certificate details. For example, when running REANA backend on user's laptop for development purposes.
Improves the VOMS proxy and the Rucio sidecar error messages in case user doesn't set …
=> job manager: respect user-supplied VOMS proxy file

CHANGES.rst, LICENSE, docs/conf.py, reana_job_controller/utils.py, requirements.in, requirements.txt, setup.py
Fixes intermittent HPC job submission issues by DNS-resolving the Slurm head node IPv4 address before establishing the connection.
Closes #368.
=> slurmcern: fix HPC job submission issues

reana_job_controller/job_monitor.py, reana_job_controller/kubernetes_job_manager.py
This commit changes the error messages used to log k8s API errors so
that each of them is unique. This will help to debug #383.
=> k8s: use unique error messages

docs/openapi.json, reana_job_controller/schemas.py, reana_job_controller/spec.py, requirements.txt, setup.py
Update to apispec v3, as the version used before is not compatible with
PyYAML v6.
Closes reanahub/reana-commons#399
=> global: update to apispec v3

.github/codecov.yml, Dockerfile, docs/openapi.json, reana_job_controller/config.py, reana_job_controller/rest.py, run-tests.sh, tests/test_job_manager.py
Adds fully qualified canonical locations of container images, making the container technology setup podman-friendly.
Closes reanahub/reana#729.
=> docker: podman-friendly image locations

CHANGES.rst, reana_job_controller/job_monitor.py, tests/conftest.py, tests/test_job_monitor.py
**job-monitor: fix deletion of failed jobs with sidecar containers**
Fix an issue where job pods were not deleted when sidecar containers
were used (e.g. to renew Kerberos tickets).
Before, updating the status of a job was not performed unless all the
containers were terminated. This does not work if only one container
fails to start (e.g. if failing to pull a docker image), while the
sidecar container keeps running.
Closes #391
**job-monitor: check all container statuses of pending pod**
Make sure that the statuses of all containers are checked when a pod is
in the `Pending` phase. Before, the checks were stopping at the first
non-waiting container, thus potentially not considering containers that
were waiting due to `ImagePullErr` or `InvalidImageName`.
**How to test**
Check that …
=> job-monitor: fix deletion of failed jobs with sidecar containers

CHANGES.rst, reana_job_controller/job_monitor.py, run-tests.sh, tests/test_job_monitor.py
- job-monitor: consider `OOMKilled` pods as failed
- tests: add support for podman
Closes #396
Note that this PR depends on #393
=> job-monitor: consider `OOMKilled` pods as failed

Dockerfile, reana_job_controller/slurmcern_job_manager.py
Fixes location of htcondorcern build dependencies that changed recently in the CERN Linux batch repositories. Closes #403.
=> docker: fix location of htcondorcern build dependencies

.github/workflows/ci.yml, run-tests.sh, setup.py
Allows execution of selected pytests via PYTESTARG environment variable. Example: `PYTESTARG=test_version ./run-tests.sh --check-pytest`.
Cleans up running DB container when some pytest segfaults.
Pins werkzeug upper version due to incompatibilities with Flask version after recent releases.
Closes reanahub/reana#755.
=> tests: allow execution of selected pytests only

.github/workflows/ci.yml, Dockerfile, requirements.in, requirements.txt
=> ci: publish docker image after new release

docs/openapi.json, reana_job_controller/htcondorcern_job_manager.py, reana_job_controller/job_db.py, reana_job_controller/job_manager.py, reana_job_controller/job_monitor.py, reana_job_controller/kubernetes_job_manager.py, reana_job_controller/rest.py, reana_job_controller/slurmcern_job_manager.py, tests/test_job_manager.py, tests/test_job_monitor.py
- refactor(job-monitor): centralise logs and status updates (#423)
- refactor(job-db): set job status also in the main database (#423)
- refactor(job-monitor): move fetching of logs to job-manager (#423)
- feat(shutdown): stop all running jobs before stopping workflow (#423)
Closes https://github.com/reanahub/reana-workflow-controller/issues/546
=> feat(shutdown): stop all running jobs before stopping workflow (#423)

.github/workflows/ci.yml, etc/job_wrapper.sh, run-tests.sh
- ci(commitlint): check for the presence of concrete PR number
Enrich commitlint checker in order to check the precise PR number in the
commit log headline.
- ci(shellcheck): fix exit code propagation
Return properly the exit code status of shellcheck command when looping
through shell script files.
=> ci(commitlint): check for the presence of concrete PR number

run-tests.sh
=> ci(pytest): move to PostgreSQL 14.10 (#429)

reana_job_controller/factory.py, reana_job_controller/job_manager.py
Up until now, to avoid keeping open idle connections with the database,
the connection pool was disposed after every request. However,
connections that are checked out at the moment of the pool disposal are
kept open, and they do not count towards the maximum number of
connections set by `SQLALCHEMY_POOL_SIZE` and `SQLALCHEMY_MAX_OVERFLOW`.
This resulted in many connections being open at the same time,
saturating the capacity of the database.
Instead of destroying the pool at each request, connections are closed
each time they are put back in the pool. The end result is the same, as
no idle connection is kept open for long periods of time. At the same
time, the pool enforces that the number of open connections is limited,
so that the database is not overwhelmed.
=> fix(database): limit the number of open database connections (#437)

.gitignore, AUTHORS.md, Dockerfile, docs/openapi.json, reana_job_controller/compute4punch_job_manager.py, reana_job_controller/config.py, reana_job_controller/job_monitor.py, reana_job_controller/schemas.py, reana_job_controller/utils.py, requirements.in, requirements.txt, setup.py
This pull request contains a job controller, job monitor and tools to support the compute4punch backend.
=> Add job controller, job monitor and tools to support compute4punch backend

reana_job_controller/config.py
Update reana-auth-vomsproxy to the latest version in order to fix VOMS proxy initialisation troubles now that WLCG IAM is in production.
=> fix(config): update reana-auth-vomsproxy to 1.2.1 to fix WLCG IAM

.github/workflows/ci.yml, setup.py
BREAKING CHANGE: drop support for Python 3.6 and 3.7
Closes reanahub/reana#784
=> build(python): drop support for Python 3.6 and 3.7 (#455)

AUTHORS.md, reana_job_controller/factory.py, reana_job_controller/job_monitor.py, reana_job_controller/kubernetes_job_manager.py, reana_job_controller/utils.py, tests/test_job_monitor.py, tests/test_utils.py
Related to https://github.com/reanahub/reana/issues/824
Fix multiline formatting. Log pod errors, evictions and other problematic events to warning log. Cover new functionality with tests.
Example logs (with FluentBit configured to collect `job-controller` logs):
OOM killed:
```
2024-09-04 11:08:11,795 | root | MainThread | INFO | Publishing step:0, cmd: python "code/helloworld.py" --inputfile "data/names.txt" --outputfile "results/greetings.txt" --sleeptime 1, total steps 1 to MQ
2024-09-04 11:08:13,734 | root | kubernetes_job_monitor | WARNING | Job reana-run-job-ad805df8-6d8c-4b00-9942-25ca994af5ad-f62zc was terminated, reason: StartError, message: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container …
```
=> feat(job_monitor): log job pod errors, disruptions to warning (#468)

AUTHORS.md, reana_job_controller/config.py, reana_job_controller/job_manager.py, tests/test_job_manager.py
This pull request contains the ongoing work of dask integration into REANA.
=> feat(dask): Dask integration (#464)

reana_job_controller/htcondorcern_job_manager.py
- **fix(htcondorcern): run provided command in unpacked image (#474)**
- **fix(htcondorcern): support multiline commands (#474)**
Closes #470
Closes #471
=> fix(htcondorcern): unpacked images and multiline commands

reana_job_controller/config.py
Update reana-auth-vomsproxy to the latest version in order to fix VOMS proxy initialisation troubles for server-side VOMS authentication techniques.
Closes reanahub/reana-auth-vomsproxy#34
=> fix(config): update reana-auth-vomsproxy to 1.3.1 to fix WLCG IAM

docs/openapi.json, reana_job_controller/config.py, reana_job_controller/kubernetes_job_manager.py, reana_job_controller/rest.py, reana_job_controller/schemas.py, requirements.txt, setup.py, tests/test_job_manager.py
Add the following settings to the Kubernetes job spec, either from user-defined values in `reana.yaml` or from administrator-defined defaults.
- `spec.containers[].resources.requests.cpu`
- `spec.containers[].resources.requests.memory`
- `spec.containers[].resources.limits.cpu`
- `spec.containers[].resources.limits.memory`.
Closes reanahub/reana#883
=> feat(kubernetes): add resource settings in kubernetess jobs

.editorconfig, .github/workflows/ci.yml, .markdownlint.yaml, .prettierignore, .prettierrc.yaml, .release-please-config.json, CHANGELOG.md, CONTRIBUTING.md, MANIFEST.in, README.md, docs/index.md, etc/job_wrapper.sh, run-tests.sh
Introduce remaining file formatting checks to `run-tests.sh` and to the GitHub CI:
Closes #490
=> ci: add remaining linting
